### PR TITLE
Create python-package-conda.yml

### PR DESCRIPTION
**Pull request by MrLucifer-pro**
workflows

### CODE REVIEW

**Comment by MrLucifer-pro** [comment]
https://github.com/MatrixTM/MHDDoS/pull/537/commits/615daf34444bb307f5001b93bc752e4e1b6a3723

**Comment by MrLucifer-pro** [comment]
https://github.com/MrLucifer-pro/MHDDoS/tree/MrLucifer-pro-patch-1

**Comment by MrLucifer-pro** [comment]
.github/workflows/python-package-conda.yml

**Comment by MrLucifer-pro** [comment]
[](.github/workflows/python-package-conda.yml

**Comment by officialrocky2005** [comment]
hello ?

**Pull request closed without merging**
